# Generated by Django 5.2.5 on 2025-08-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeface', '0003_cart_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_active',
            new_name='is_Active',
        ),
    ]
