# Generated by Django 5.2.5 on 2025-08-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeface', '0004_rename_is_active_cart_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
