# Generated by Django 5.2.5 on 2025-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
