# Generated by Django 5.2.5 on 2025-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_vendor_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_approved',
            field=models.BooleanField(default=True),
        ),
    ]
