# Generated by Django 5.2.5 on 2025-08-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_vendor_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
