# Generated by Django 5.2.5 on 2025-08-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_by', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'product')},
        ),
    ]
